import { makeStyles } from "tss-react/mui";

export const useCompleteDayStyles = makeStyles()({
  container: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    height: "100dvh",
    padding: "65px 15px 90px",
    overflow: "scroll",
  },
  box: {
    width: "100%",
    borderRadius: "10px",
    background: "#58585b",
    padding: "10px 10px 0px",
  },
  exerciseContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    borderRadius: "10px",
    marginBottom: "20px",
    border: "solid 5px",
    boxShadow: "0px 5px 10px #131314",
  },
  horizontalDivider: {
    width: "100%",
    height: "2px",
    background: "black",
    marginBottom: "10px",
    border: "solid",
    borderWidth: "1px",
  },
  descText: {
    fontFamily: "League+Spartan",
    fontWeight: 600,
    fontSize: "10px",
  },
  entryTitle: {
    fontFamily: "League+Spartan",
    fontSize: "16px",
    fontWeight: 600,
    color: "white",
  },
  exerciseTop: {
    width: "95%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  editButton: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "30px",
    width: "30px",
    background: "#0096FF",
    color: "white",
    border: "solid 1px white",
    borderRadius: "5px",
    fontSize: "20px",
  },
  leftPad: {
    width: "30px",
  },
  eName: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textWrap: "nowrap",
    borderRadius: "5px 5px 0px 0px",
    padding: "5px 0px 10px",
  },
  entry: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    marginBottom: "10px",
    textAlign: "center",
    justifyContent: "center",
    color: "white",
  },
  entryName: {
    fontFamily: "League+Spartan",
    fontSize: "16px",
    fontWeight: 400,
  },
  entrySetsReps: {
    marginRight: "5px",
  },
  entryWeight: {
    margin: "0px 5px 0px 10px",
  },
  input: {
    border: "solid",
    borderColor: "gray",
    borderWidth: "1px",
    borderRadius: "5px",
    width: "100%",
    background: "white",
    fontSize: "16px",
    marginRight: "5px",
  },
  noteName: {
    fontFamily: "League+Spartan",
    fontSize: "16px",
    fontWeight: 400,
    whiteSpace: "nowrap",
    marginRight: "5px",
  },
  noteInput: {
    border: "solid",
    borderColor: "gray",
    borderWidth: "1px",
    borderRadius: "5px",
    width: "100%",
    background: "white",
    fontSize: "16px",
    paddingLeft: "5px",
  },
  actions: {
    display: "flex",
    width: "100%",
    justifyContent: "space-around",
    marginBottom: "10px",
  },
  buttonContainer: {
    width: "100%",
    height: "35px",
  },
  actionButton: {
    width: "100%",
    height: "30px",
    border: "none",
    color: "white",
    fontFamily: "League+Spartan",
    fontSize: "16px",
    fontWeight: 600,
    "&:hover": {
      cursor: "pointer",
    },
  },
  prevButtonTop: {
    borderRadius: "5px 0px 0px 5px",
    background: "#a3258c",
    transform: "translateY(-30px)",
    transition: "transform 0.1s",
    "&:active": {
      transform: "translateY(-27px)",
    },
  },
  prevButtonBottom: {
    borderRadius: "5px 0px 0px 5px",
    background: "#5f1652",
    transform: "translateY(5px)",
  },
  nextButtonTop: {
    background: "#0096FF",
    transform: "translateY(-30px)",
    transition: "transform 0.1s",
    "&:active": {
      transform: "translateY(-27px)",
    },
  },
  nextButtonBottom: {
    background: "#004c81",
    transform: "translateY(5px)",
  },
  nextButtonSide: {
    borderRadius: "5px 0px 0px 5px",
  },
  pauseButtonTop: {
    borderRadius: "0px 5px 5px 0px",
    background: "red",
    transform: "translateY(-30px)",
    transition: "transform 0.1s",
    "&:active": {
      transform: "translateY(-27px)",
    },
    textDecoration: "none",
  },
  pauseButtonBottom: {
    borderRadius: "0px 5px 5px 0px",
    background: "#830000",
    transform: "translateY(5px)",
  },
  changeSetButtonContainer: {
    width: "20px",
    height: "23px",
  },
  leftContainer: {
    marginRight: "5px",
  },
  rightContainer: {
    marginLeft: "5px",
  },
  changeSetButton: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "20px",
    color: "white",
    "&:hover": {
      cursor: "pointer",
    },
  },
  addSetButtonTop: {
    background: "#0096FF",
    height: "20px",
    borderRadius: "10px",
    transform: "translateY(-20px)",
    transition: "transform 0.1s",
    "&:active": {
      transform: "translateY(-18px)",
    },
  },
  addSetButtonBottom: {
    background: "#004c81",
    height: "15px",
    width: "20px",
    borderRadius: "0px 0px 10px 10px",
    transform: "translateY(3px)",
  },
  subtractSetButtonTop: {
    background: "red",
    height: "20px",
    borderRadius: "10px",
    transform: "translateY(-20px)",
    transition: "transform 0.1s",
    "&:active": {
      transform: "translateY(-18px)",
    },
  },
  subtractSetButtonBottom: {
    background: "#830000",
    height: "15px",
    width: "20px",
    borderRadius: "0px 0px 10px 10px",
    transform: "translateY(3px)",
  },
  changeSetIcon: {
    fontSize: "18px",
  },
  setsEntry: {
    display: "flex",
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
    color: "white",
  },
  sets: {
    marginBottom: "10px",
  },
  finish: {
    color: "white",
    fontFamily: "League+Spartan",
    fontSize: "16px",
    fontWeight: 600,
  },
});
