import { makeStyles } from "tss-react/mui";

export const useCreateAccountStyles = makeStyles()({
  container: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    height: "100dvh",
    padding: "65px 15px 85px",
    overflow: "scroll",
  },
  box: {
    width: "100%",
    borderRadius: "10px",
    background: "#58585b",
    padding: "10px 10px 0px",
  },
  titleContainer: {
    display: "flex",
    width: "100%",
    justifyContent: "center",
  },
  title: {
    fontFamily: "League+Spartan",
    fontWeight: 700,
    fontSize: "22px",
    marginBottom: "10px",
    color: "white",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    color: "white",
    background: "#3a3a3d",
    fontFamily: "League+Spartan",
    fontSize: "14px",
    marginBottom: "10px",
    width: "100%",
    justifyContent: "center",
    alignItems: "center",
    padding: "10px",
    borderRadius: "5px",
    whiteSpace: "nowrap",
  },
  horizontalDivider: {
    width: "100%",
    height: "2px",
    background: "black",
    marginBottom: "10px",
    border: "solid",
    borderWidth: "1px",
  },
  entry: {
    display: "flex",
    alignItems: "center",
    marginBottom: "10px",
    width: "100%",
    justifyContent: "flex-start",
  },
  entryName: {
    fontFamily: "League+Spartan",
    width: "60%",
    fontWeight: 600,
    fontSize: "16px",
  },
  input: {
    border: "solid",
    borderColor: "gray",
    borderWidth: "1px",
    borderRadius: "5px",
    marginLeft: "5px",
    width: "100%",
    paddingLeft: "5px",
    fontSize: "16px",
    background: "white",
  },
  dateInput: {
    paddingLeft: "0px",
    background: "white",
  },
  actions: {
    display: "flex",
    width: "100%",
    justifyContent: "space-around",
    marginBottom: "10px",
  },
  buttonContainer: {
    width: "100%",
    height: "35px",
  },
  actionButton: {
    width: "100%",
    height: "30px",
    border: "none",
    color: "white",
    fontFamily: "League+Spartan",
    fontSize: "16px",
    fontWeight: 600,
    "&:hover": {
      cursor: "pointer",
    },
  },
  submitButtonTop: {
    borderRadius: "5px 0px 0px 5px",
    background: "#0096FF",
    transform: "translateY(-30px)",
    transition: "transform 0.1s",
    "&:active": {
      transform: "translateY(-27px)",
    },
  },
  submitButtonBottom: {
    borderRadius: "5px 0px 0px 5px",
    background: "#004c81",
    transform: "translateY(5px)",
  },
  cancelButtonTop: {
    borderRadius: "0px 5px 5px 0px",
    background: "red",
    transform: "translateY(-30px)",
    transition: "transform 0.1s",
    "&:active": {
      transform: "translateY(-27px)",
    },
  },
  cancelButtonBottom: {
    borderRadius: "0px 5px 5px 0px",
    background: "#830000",
    transform: "translateY(5px)",
  },
});
