import { ExpoConfig, ConfigContext } from "expo/config";
import { withXcodeProject, ConfigPlugin } from "@expo/config-plugins";

// Apple Developer team used to code-sign local dev builds. Required because the
// Sign in with Apple entitlement (expo-apple-authentication) can't be ad-hoc
// signed — without a team, `expo run:ios` fails with "No code signing
// certificates". `ios/` is gitignored and regenerated by prebuild, so we stamp
// DEVELOPMENT_TEAM in via a mod on every prebuild rather than setting it once
// in Xcode (which would be wiped). EAS Build manages its own cloud signing and
// ignores this.
const APPLE_TEAM_ID = "622PWJ5CNW";

const withDevelopmentTeam: ConfigPlugin<string> = (config, teamId) =>
  withXcodeProject(config, (cfg) => {
    const buildConfigs = cfg.modResults.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(buildConfigs)) {
      const buildSettings = buildConfigs[key]?.buildSettings;
      // Only the app target's configs carry a bundle id; skip Pods/others.
      if (buildSettings?.PRODUCT_BUNDLE_IDENTIFIER) {
        buildSettings.DEVELOPMENT_TEAM = teamId;
      }
    }
    return cfg;
  });

// Reverse-DNS app id. react-native-auth0 hardcodes its native callback scheme
// to `{BUNDLE_ID}.auth0` (NativeWebAuthProvider), so the Auth0 dashboard's
// allowed callback/logout URLs must be:
//   app.liftledger.mobile.auth0://{AUTH0_DOMAIN}/ios/{BUNDLE_ID}/callback
//   app.liftledger.mobile.auth0://{AUTH0_DOMAIN}/android/{BUNDLE_ID}/callback
// We don't pass a customScheme to the plugin so its Info.plist registration
// defaults to the same `{BUNDLE_ID}.auth0` scheme the runtime uses.
const BUNDLE_ID = "app.liftledger.mobile";

const AUTH0_DOMAIN = process.env.EXPO_PUBLIC_AUTH0_DOMAIN;

// This dynamic config is the single source of truth for the Expo app config
// (there is intentionally no app.json). `version` is the user-facing marketing
// version; the iOS build number is managed remotely by EAS (eas.json
// `appVersionSource: "remote"` + production `autoIncrement`).
export default ({ config }: ConfigContext): ExpoConfig => {
  const expoConfig: ExpoConfig = {
    ...config,
    name: "LiftLedger",
    slug: "liftledger",
    owner: "liftledger",
    version: "1.0.0",
    orientation: "portrait",
    icon: "./assets/icon.png",
    scheme: BUNDLE_ID,
    userInterfaceStyle: "automatic",
    extra: {
      ...config.extra,
      eas: {
        projectId: "07ddf7be-e66c-4aa8-b47c-32fd2c4da423",
      },
    },
    ios: {
      ...config.ios,
      bundleIdentifier: BUNDLE_ID,
      supportsTablet: true,
    },
    android: {
      ...config.android,
      package: BUNDLE_ID,
      adaptiveIcon: {
        backgroundColor: "#E6F4FE",
        foregroundImage: "./assets/android-icon-foreground.png",
        backgroundImage: "./assets/android-icon-background.png",
        monochromeImage: "./assets/android-icon-monochrome.png",
      },
      predictiveBackGestureEnabled: false,
    },
    web: {
      favicon: "./assets/favicon.png",
    },
    plugins: [
      [
        "react-native-auth0",
        {
          domain: AUTH0_DOMAIN,
        },
      ],
      "@react-native-community/datetimepicker",
      "expo-apple-authentication",
      [
        "expo-splash-screen",
        {
          image: "./assets/logo.png",
          imageWidth: 50,
          resizeMode: "contain",
          backgroundColor: "#ffffff",
          dark: {
            image: "./assets/logo.png",
            backgroundColor: "#131314",
          },
        },
      ],
    ],
  };

  return withDevelopmentTeam(expoConfig, APPLE_TEAM_ID);
};
