export const EXERCISE_NAMES: string[] = [
  "Bench Press",
  "Incline Bench Press",
  "Chest Press",
  "Squeeze Press",
  "Standing Chest Fly",
  "Seated Chest Fly",
  "Plate-loaded Chest Press",
  "Chest Dip",
  "Standing Overhead Press",
  "Seated Overhead Press",
  "Arnold Press",
  "Front Raise",
  "Lateral Raise",
  "Bent Over Row",
  "Reverse Grip Row",
  "Chest Supported Row",
  "Pendlay Row",
  "Seated Row",
  "Close Grip Seated Row",
  "Wide Grip Seated Row",
  "Pullup",
  "Chinup",
  "Pulldown",
  "Wide Grip Pulldown",
  "Close Grip Pulldown",
  "Reverse Grip Pulldown",
  "Diverging Pulldown",
  "T-Bar Row",
  "Single Arm Dumbbell Row",
  "Pullover",
  "Rear Delt Fly",
  "Face Pull",
  "Kelso Shrug",
  "Good Morning",
  "Back Extension",
  "Back Squat",
  "Front Squat",
  "Zercher Squat",
  "Hack Squat",
  "Leg Press",
  "Deadlift",
  "Romanian Deadlift",
  "Hamstring Curl",
  "Leg Extension",
  "Calf Raise",
  "Hip Thrust",
  "Hip Adduction",
  "Hip Abduction",
  "Split Squat",
  "Bulgarian Split Squat",
  "Lunge",
  "Reverse Lunge",
  "Shrug",
  "Farmer's Carry",
  "Suitcase Carry",
  "Bicep Curl",
  "Hammer Curl",
  "Cross-body Hammer Curl",
  "Preacher Curl",
  "Spider Curl",
  "Incline Curl",
  "Reverse Curl",
  "Zottman Curl",
  "Concentration Curl",
  "Standing Overhead Extension",
  "Seated Overhead Extension",
  "Tricep Cross-body Extension",
  "Tricep Pushdown",
  "Tricep Dip",
  "Skullcrusher",
  "Close Grip Press",
  "Flat JM Press",
  "Incline JM Press",
  "Tricep Kickback",
  "Forearm Curl",
  "Reverse Forearm Curl",
  "Crunch",
  "Decline Crunch",
  "Cable Crunch",
  "Lying Cable Crunch",
  "Lying Leg Raise",
  "Hanging Knee Raise",
  "Hanging Leg Raise",
  "Russian Twist",
];
