export const EXERCISE_NAMES: string[] = [
  "Arnold Press",
  "Back Extension",
  "Back Squat",
  "Bench Press",
  "Bent Over Row",
  "Bicep Curl",
  "Bulgarian Split Squat",
  "Cable Crunch",
  "Calf Raise",
  "Chest Dip",
  "Chest Fly",
  "Chest Press",
  "Chest-supported Row",
  "Chinup",
  "Close Grip Press",
  "Close Grip Pulldown",
  "Close Grip Seated Row",
  "Concentration Curl",
  "Cross-body Hammer Curl",
  "Crunch",
  "Deadlift",
  "Decline Crunch",
  "Diverging Pulldown",
  "Face Pull",
  "Farmer's Carry",
  "Flat JM Press",
  "Forearm Curl",
  "Front Raise",
  "Front Squat",
  "Good Morning",
  "Hack Squat",
  "Hammer Curl",
  "Hamstring Curl",
  "Hanging Knee Raise",
  "Hanging Leg Raise",
  "Hip Abduction",
  "Hip Adduction",
  "Hip Thrust",
  "Incline Bench Press",
  "Incline Curl",
  "Incline JM Press",
  "Kelso Shrug",
  "Lat Pulldown",
  "Lateral Raise",
  "Leg Extension",
  "Leg Press",
  "Lunge",
  "Lying Cable Crunch",
  "Lying Leg Raise",
  "Pendlay Row",
  "Plate-loaded Chest Press",
  "Preacher Curl",
  "Pullover",
  "Pullup",
  "Rear Delt Fly",
  "Reverse Curl",
  "Reverse Forearm Curl",
  "Reverse Grip Pulldown",
  "Reverse Grip Row",
  "Reverse Lunge",
  "Romanian Deadlift",
  "Russian Twist",
  "Seated Chest Fly",
  "Seated Overhead Extension",
  "Seated Overhead Press",
  "Seated Row",
  "Shrug",
  "Single Arm Dumbbell Row",
  "Skullcrusher",
  "Spider Curl",
  "Split Squat",
  "Squeeze Press",
  "Standing Chest Fly",
  "Standing Overhead Extension",
  "Standing Overhead Press",
  "Suitcase Carry",
  "T-Bar Row",
  "Tricep Cross-body Extension",
  "Tricep Dip",
  "Tricep Kickback",
  "Tricep Pushdown",
  "Wide Grip Pulldown",
  "Wide Grip Seated Row",
  "Zercher Squat",
  "Zottman Curl",
];
