export const EXERCISE_NAMES: string[] = [
  "Arnold Press",
  "Back Extension",
  "Back Squat",
  "Bench Press",
  "Bent Over Row",
  "Bicep Curl",
  "Bulgarian Split Squat",
  "Cable Crunch",
  "Calf Raise",
  "Chest Dip",
  "Chest Fly",
  "Chest Press",
  "Chest-supported Row",
  "Chinup",
  "Close-grip Bench Press",
  "Close-grip Pulldown",
  "Close-grip Seated Row",
  "Concentration Curl",
  "Cross-body Hammer Curl",
  "Crunch",
  "Deadlift",
  "Decline Crunch",
  "Diverging Pulldown",
  "Face Pull",
  "Farmer's Carry",
  "JM Press",
  "Forearm Curl",
  "Front Raise",
  "Front Squat",
  "Good Morning",
  "Hack Squat",
  "Hammer Curl",
  "Hamstring Curl",
  "Hanging Knee Raise",
  "Hanging Leg Raise",
  "Hip Abduction",
  "Hip Adduction",
  "Hip Thrust",
  "Incline Bench Press",
  "Incline Curl",
  "Incline JM Press",
  "Kelso Shrug",
  "Lat Pulldown",
  "Lateral Raise",
  "Leg Extension",
  "Leg Press",
  "Lunge",
  "Lying Cable Crunch",
  "Lying Leg Raise",
  "Pendlay Row",
  "Plate-loaded Chest Press",
  "Preacher Curl",
  "Pullover",
  "Pullup",
  "Rear Delt Fly",
  "Reverse-grip Curl",
  "Reverse-grip Pulldown",
  "Reverse-grip Row",
  "Reverse-grip Wrist Curl",
  "Reverse Lunge",
  "Romanian Deadlift",
  "Russian Twist",
  "Seated Chest Fly",
  "Seated Overhead Extension",
  "Seated Overhead Press",
  "Seated Row",
  "Shrug",
  "Single-arm Dumbbell Row",
  "Single-arm Lateral Raise",
  "Single-arm Rear Delt Fly",
  "Skullcrusher",
  "Spider Curl",
  "Split Squat",
  "Squeeze Press",
  "Standing Chest Fly",
  "Standing Overhead Extension",
  "Standing Overhead Press",
  "Suitcase Carry",
  "T-Bar Row",
  "Tricep Cross-body Extension",
  "Tricep Dip",
  "Tricep Kickback",
  "Tricep Pushdown",
  "Wide-grip Pulldown",
  "Wide-grip Seated Row",
  "Wrist Curl",
  "Zercher Squat",
  "Zottman Curl",
];
